export const PRODUCT_CATEGORIES = [
  "Antiques",
  "Art",
  "Automotive and Vehicles",
  "Baby Products",
  "Beauty and Personal Care",
  "Books, Movies and Music",
  "Business and Industrial",
  "Cameras and Photo",
  "Cell Phones and Accessories",
  "Clothing, Shoes and Jewelry",
  "Collectibles",
  "Computers and Accessories",
  "Crafts and Handmade",
  "Electronics and Gadgets",
  "Furniture",
  "Garden and Outdoors",
  "Groceries and Food",
  "Health and Household",
  "Home and Kitchen",
  "Jewelry and Accessories",
  "Musical Instruments",
  "Office Supplies",
  "Pet Supplies",
  "Sports and Fitness",
  "Tools and Home Improvement",
  "Toys and Games",
  "Video Games"
];
